const filters = [
  {
    id: "operation",
    type: "radio",
    size: { xs: 12, lg: 2 },
    options: [
      { id: "rent", label: "getInTouch_form.radio.option1.label" },
      { id: "buy", label: "getInTouch_form.radio.option2.label" },
    ],
    defaultSelectedOption: "rent",
    isLabelVisible: false,
    label: "getInTouch_form.radio.title",
  },
  {
    id: "location",
    size: { xs: 12, lg: 6 },
    type: "searchLocation",
    options: [
      { id: "rent", label: "getInTouch_form.radio.option1.label" },
      { id: "buy", label: "getInTouch_form.radio.option2.label" },
    ],
    isLabelVisible: false,
    leftIcon: "FaSearch",
    showSuggestionsOnFocus: true,
    clearButton: true,
    placeholder: "Type a location...",
    label: "getInTouch_form.radio.title",
  },
  {
    id: "category",
    size: { xs: 12, lg: 4 },

    type: "autosuggest",
    options: [
      { id: "department", label: "Department" },
      { id: "house", label: "House" },
      { id: "garage", label: "Garage" },
      { id: "office", label: "Office" },
      { id: "yard", label: "Yard" },
    ],
    isLabelVisible: false,
    showSuggestionsOnFocus: true,
    placeholder: "What are you looking...",
    rightIcon: "FaChevronDown",
    label: "getInTouch_form.radio.title",
  },
  {
    id: "price_from",
    label: "getInTouch_form.nameInput",
    size: { xs: 12, lg: 3 },
    isLabelVisible: false,
    placeholder: "Price from:",
    type: "autosuggest",
    clearButton: true,
    showSuggestionsOnFocus: true,
    options: [
      { id: "0", label: "0" },
      { id: "20000", label: "20.000,00 $" },
      { id: "50000", label: "50.000,00 $" },
      { id: "100000", label: "100.000,00 $" },
      { id: "120000", label: "120.000,00 $" },
      { id: "150000", label: "150.000,00 $" },
      { id: "170000", label: "170.000,00 $" },
      { id: "190000", label: "190.000,00 $" },
      { id: "220000", label: "220.000,00 $" },
    ],
  },
  {
    id: "price_to",
    label: "getInTouch_form.nameInput",
    size: { xs: 12, lg: 3 },
    isLabelVisible: false,
    placeholder: "Price To:",
    showSuggestionsOnFocus: true,
    clearButton: true,
    type: "autosuggest",
    options: [
      { id: "0", label: "0" },
      { id: "20000", label: "20.000,00 $" },
      { id: "50000", label: "50.000,00 $" },
      { id: "100000", label: "100.000,00 $" },
      { id: "120000", label: "120.000,00 $" },
      { id: "150000", label: "150.000,00 $" },
      { id: "170000", label: "170.000,00 $" },
      { id: "190000", label: "190.000,00 $" },
      { id: "220000", label: "220.000,00 $" },
    ],
  },
  {
    id: "area_from",
    label: "getInTouch_form.nameInput",
    type: "text",
    size: { xs: 12, lg: 3 },
    isLabelVisible: false,
    placeholder: "Area m2 from:",
  },
  {
    id: "area_to",
    label: "getInTouch_form.nameInput",
    type: "text",
    size: { xs: 12, lg: 3 },
    isLabelVisible: false,
    placeholder: "Area m2 To:",
  },
  {
    id: "amenities",
    label: "getInTouch_form.nameInput",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "Amenities:",
    showSuggestionsOnFocus: true,
    type: "multiselect",
    options: [
      { id: "Swimming Pool", label: "Swimming Pool" },
      { id: "Garden", label: "Garden" },
      { id: "Gym", label: "Gym" },
      { id: "Balcony", label: "Balcony" },
      { id: "Parking", label: "Parking" },
      { id: "Security System", label: "Security System" },
      { id: "En-suite Bathroom", label: "En-suite Bathroom" },
      { id: "Walk-in Closet", label: "Walk-in Closet" },
      { id: "Fireplace", label: "Fireplace" },
      { id: "Natural Light", label: "Natural Light" },
      { id: "Workshop Area", label: "Workshop Area" },
      { id: "Security System", label: "Security System" },
      { id: "Storage Shelves", label: "Storage Shelves" },
      { id: "Electric Door Opener", label: "Electric Door Opener" },
    ],
  },
  {
    id: "description",
    label: "getInTouch_form.nameInput",
    type: "text",
    size: { xs: 12, lg: 6 },
    isLabelVisible: false,
    placeholder: "Part of description:",
  },
  {
    id: "rooms",
    type: "radio",
    size: { xs: 12, lg: 6 },
    options: [
      { id: "0", label: "0" },
      { id: "1", label: "1+" },
      { id: "2", label: "2+" },
      { id: "3", label: "3+" },
      { id: "4", label: "4+" },
      { id: "5", label: "5+" },
    ],
    defaultSelectedOption: "0",
    label: "Rooms",
  },
  {
    id: "bathrooms",
    type: "radio",
    size: { xs: 12, lg: 6 },
    options: [
      { id: "0", label: "0" },
      { id: "1", label: "1+" },
      { id: "2", label: "2+" },
      { id: "3", label: "3+" },
      { id: "4", label: "4+" },
      { id: "5", label: "5+" },
    ],
    defaultSelectedOption: "0",
    label: "Bathrooms",
  },
];

export const FILTERS = {
  type: "post",
  inputs: filters,
  hasSubmit: false,
  buttonLabel: "Search",
};
